name: Deploy to Amazon Secret Manager
on:
  push:
    branches:
      - main
  pull_request:
      branches: [ main ]

  workflow_dispatch:
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2
